https://towardsdev.com/how-to-calculate-correlation-in-python-part-iii-f98b82f7ace4

In [1]:
import numpy as np
import scipy.stats
x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
z = np.array([5, 3, 2, 1, 0, -2, -8, -11, -15, -16])

print('Array x ranking: ', scipy.stats.rankdata(x))
print('Array y ranking: ', scipy.stats.rankdata(y))
print('Array z ranking: ', scipy.stats.rankdata(z))

Array x ranking:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array y ranking:  [ 2.  1.  3.  4.  5.  6.  7.  8. 10.  9.]
Array z ranking:  [10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [2]:
scipy.stats.rankdata([8,2,0,2])

array([4. , 2.5, 1. , 2.5])

In [3]:
scipy.stats.rankdata([8,2,0,2],method='min')

array([4, 2, 1, 2], dtype=int64)

In [4]:
scipy.stats.rankdata([8,2,0,2],method='max')

array([4, 3, 1, 3], dtype=int64)

In [5]:
scipy.stats.rankdata([8,np.nan,0,2],method='max')

array([3, 4, 1, 2], dtype=int64)

In [6]:
np.argsort(y)+1

array([ 2,  1,  3,  4,  5,  6,  7,  8, 10,  9], dtype=int64)

In [7]:
result=scipy.stats.spearmanr(x,y)
result

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [8]:
result.correlation

0.9757575757575757

In [9]:
result.pvalue

1.4675461874042197e-06

In [12]:
rho,p = scipy.stats.spearmanr(x,y)
print(rho,p)

0.9757575757575757 1.4675461874042197e-06


In [14]:
xy=np.array([list(x),list(y)])
rho,p=scipy.stats.spearmanr(xy,axis=1)
print(rho,p)

0.9757575757575757 1.4675461874042197e-06


In [15]:
xyz=np.array([list(x),list(y),list(z)])
corr_matrix,p_matrix=scipy.stats.spearmanr(xyz,axis=1)

In [16]:
corr_matrix

array([[ 1.        ,  0.97575758, -1.        ],
       [ 0.97575758,  1.        , -0.97575758],
       [-1.        , -0.97575758,  1.        ]])

In [17]:
p_matrix

array([[6.64689742e-64, 1.46754619e-06, 6.64689742e-64],
       [1.46754619e-06, 6.64689742e-64, 1.46754619e-06],
       [6.64689742e-64, 1.46754619e-06, 6.64689742e-64]])

In [19]:
result=scipy.stats.kendalltau(x,y)
print(result)
print(result.correlation)
print(result.pvalue)

KendalltauResult(correlation=0.911111111111111, pvalue=2.9761904761904762e-05)
0.911111111111111
2.9761904761904762e-05


In [20]:
tau,p = scipy.stats.kendalltau(x,y)

In [21]:
print(tau,p)

0.911111111111111 2.9761904761904762e-05


In [22]:
import pandas as pd

x, y, z = pd.Series(x), pd.Series(y), pd.Series(z)
xy = pd.DataFrame({'x': x, 'y': y})
xyz = pd.DataFrame({'x': x, 'y': y, 'z': z})

In [23]:
x.corr(y,method='spearman')

0.9757575757575757

In [24]:
xy.corr(method='spearman')

x         y
x  1.000000  0.975758
y  0.975758  1.000000

In [25]:
xy.corrwith(z,method='spearman')

x   -1.000000
y   -0.975758
dtype: float64

In [26]:
x.corr(y,method='kendall')

0.911111111111111

In [27]:
xy.corr(method='kendall')

x         y
x  1.000000  0.911111
y  0.911111  1.000000

In [28]:
xyz.corr(method='kendall')

x         y         z
x  1.000000  0.911111 -1.000000
y  0.911111  1.000000 -0.911111
z -1.000000 -0.911111  1.000000

In [29]:
xyz.corrwith(z,method='kendall')

x   -1.000000
y   -0.911111
z    1.000000
dtype: float64