https://pub.towardsai.net/numpy-guide-super-simple-way-to-learn-it-in-10-minutes-d382ff45e215

In [1]:
import numpy as np  # Importing NumPy module

a = np.array([1, 2, 3])  # Creating a one-dimensional array
print(a)  
# Output: [1 2 3]

[1 2 3]


In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print(a.shape)  # Output: (2, 3)
print(a.size)  # Output: 6
print(a.dtype)  # Output: int64

(2, 3)
6
int32


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
c = a + b
print(c)  # Output: [5 7 9]

# Subtraction
c = a - b
print(c)  # Output: [-3 -3 -3]

# Multiplication
c = a * b
print(c)  # Output: [ 4 10 18]

# Division
c = a / b
print(c)  # Output: [0.25 0.4  0.5 ]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])  # Output: 1

1


In [5]:
print(a[1:4])  # Output: [2 3 4]

[2 3 4]


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 1])  # Output: 2, selects a specific element
print(b[1:])  # Output: [[4, 5, 6], [7, 8, 9]], slices rows
print(b[:, 1])  # Output: [2, 5, 8], selects a specific column

2
[[4 5 6]
 [7 8 9]]
[2 5 8]


In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = 2

# Broadcasting in action
c = a * b
print(c)  # Output: [2 4 6]

[2 4 6]


In [8]:
# Vectorization in action
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)  # Output: [5 7 9]

[5 7 9]


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

# Sum of array elements
print(np.sum(a))  # Output: 15

# Mean of array elements
print(np.mean(a))  # Output: 3.0

# Reshape array
b = np.reshape(a, (5, 1))
print(b)
# Output: 
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]

15
3.0
[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)
# Output: 
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stacking
c = np.vstack((a, b))
print(c)
# Output: 
# [[1 2 3]
#  [4 5 6]]

# Horizontal stacking
d = np.hstack((a, b))
print(d)  # Output: [1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Vertical splitting
b = np.vsplit(a, 2)
print(b)  
# Output: 
# [array([[1, 2, 3]]), array([[4, 5, 6]])]

# Horizontal splitting
c = np.hsplit(a, 3)
print(c)  
# Output: 
# [array([[1],[4]]), array([[2],[5]]), array([[3],[6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [13]:
import numpy as np

a = np.random.rand()
print(a)

0.5245789652570332


In [14]:
b = np.random.randint(1, 10, size=(3,3))
print(b)

[[5 2 5]
 [6 5 3]
 [9 3 5]]


In [15]:
a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))  # Output: 3.0
print(np.median(a))  # Output: 3.0
print(np.std(a))  # Output: 1.4142135623730951

3.0
3.0
1.4142135623730951
