https://python.plainenglish.io/mastering-numpy-a-data-enthusiasts-essential-companion-392cdbe39e84

In [2]:
import numpy as np

# Creating an integer array with explicit dtype, which is not necessary.
int_array = np.array([1, 2, 3], dtype=np.int32)

# Create an 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Create an array of 10 equally spaced values from 0 to 1
linspace_arr = np.linspace(0, 1, 10)

# Create an array of 5 values spaced logarithmically from 1 to 100
logspace_arr = np.logspace(0, 2, 5)

# Create an array of values from 0 to 9 with a step size of 2
arange_arr = np.arange(0, 10, 2)

# Create a 3x3 array filled with zeros
zeros_arr = np.zeros((3, 3))

# Create a 2x4 array filled with ones
ones_arr = np.ones((2, 4))

# Create a new array filled with zeros, 
# matching the shape and data type of the original array
zeros_array = np.zeros_like(original_array)

# Create a new array filled with ones, 
# matching the shape and data type of the original array
ones_array = np.ones_like(original_array)

In [3]:
# Creating a 1D array (Vector)
arr_1d = np.array([1, 2, 3])
# Dimesion: 1 , Shape: (3,), Size: 3
print(f"Dimension: {arr_1d.ndim}, Shape: {arr_1d.shape}, size: {arr_1d.size}")

# Creating a 2D array (Matrix) # Dimension: 2 , Shape: (2, 3)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) 

# Creating a 3D array (Tensor) # Dimension: 3 , Shape: (2, 2, 2)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Dimension: 1, Shape: (3,), size: 3


In [4]:
# Creating a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
first_element = arr[0]  # Access the first element (10)

# Accessing elements using negative indices
last_element = arr[-1]  # Access the last element (50)

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing along rows and columns
sliced_array = arr_2d[0,1]  # Element at row 0, column 1 (value: 2)

In [5]:
# Slicing the array to create a new array
sliced_array = arr[1:4]  # Slice from index 1 to 3 (exclusive) [20,30,40]

# Slicing with a step of 2
sliced_array = arr[0::2]  # Start at index 0, step by 2 [10,30,50]

# Slicing with negative index
second_to_last = arr[-2::]  # Access the last two elements [40,50]

# Conditional slicing: Select elements greater than 30
sliced_array = arr[arr > 30]  # Result: [40, 50]

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing along rows and columns
sliced_array = arr_2d[1:3, 0:2] # Slice a 2x2 subarray: [[4, 5], [7, 8]]

In [6]:
# Creating 1D NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
scalar = 2

# Addition
result_add = arr1 + arr2  # [5, 7, 9]

# Multiplication, Similarly subraction and division as well.
result_mul = arr1 * arr2  # [4, 10, 18]

# Creating 2D NumPy arrays
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Multiplication (element-wise, not matrix multiplication)
result_mul = matrix1 * matrix2  # [[5, 12], [21, 32]]

# Actual Matrix Multiplication using np.dot
matrix_multiplication = np.dot(matrix1,matrix2)

# Broadcasting: Multiply array by a scalar
result = arr1 * scalar  # [2, 4, 6]

In [7]:
# Create an array
original_array = np.array([1, 2, 3])

# Append elements in-place
original_array = np.append(original_array, [4, 5, 6])

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Remove the item at index 2 (value 3)
new_arr = np.delete(arr, 2)

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4,5, 6], [7, 8, 9]])

# Remove the second row (index 1)
new_arr = np.delete(arr, 1, axis=0)

In [8]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Aggregation functions
mean_value = np.mean(arr)  # Mean: 3.0
median_value = np.median(arr) # Median: 3.0
variance = np.var(arr) # Variance 2.0
standard_deviation = np.std(arr) # std: 1.414

sum_value = np.sum(arr)    # Sum: 15
min_value = np.min(arr)    # Minimum: 1
max_value = np.max(arr)    # Maximum: 5


# Universal functions
sqrt_arr = np.sqrt(arr) # Square Root
exp_arr = np.exp(arr) # Exponential

In [9]:
import numpy as np

# Creating 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Here as we are passing only 6, it will conver the 2d array to a 1d array
# with 6 elements, you cannot pass anything other than 6,
# as it doesn't match the original array!
arr_1d = arr_2d.reshape(6)

# Creating 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# converting 1D array to 2D
arr_2d = arr_1d.reshape(2, 3)

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate along the 0-axis (rows)
combined = np.concatenate((arr1, arr2)) # Result: [1, 2, 3, 4, 5, 6]

# Vertical stacking
vertical_stack = np.vstack((arr1, arr2)) # Result: [[1, 2, 3], [4, 5, 6]]

# Horizontal stacking
horizontal_stack = np.hstack((arr1, arr2)) # Result: [1, 2, 3, 4, 5, 6]

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into three equal parts
split_arr = np.split(arr, 3) 

# Result: [array([1, 2]), array([3, 4]), array([5, 6])].

In [12]:
original_arr = np.array([1, 2, 3])

# alias of original array
alias_arr = original_arr

# Changes to view_arr will affect the original array
view_arr = original_arr.view()

# Changes to copy_arr won't affect the original array
copy_arr = original_arr.copy()

In [13]:
data = np.array([3, 1, 5, 2, 4])
sorted_data = np.sort(data)  # Ascending order
reverse_sorted_data = np.sort(data)[::-1]  # Descending order

# You can also retrieve the indices that would sort the data.
data = np.array([3, 1, 5, 2, 4])

# Returns Indices that would sort the array.
sorted_indices = np.argsort(data) 

In [14]:
# Create a NumPy array with missing values
data = np.array([1, 2, np.nan, 4, np.nan, 6])

# Check for missing values
has_missing = np.isnan(data)
print(has_missing)

[False False  True False  True False]


In [15]:
# Create a 2D array with missing values
data = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])

# Remove rows with any missing values
cleaned_data = data[~np.any(np.isnan(data), axis=1)]
print(cleaned_data) # Result: [[1,2,3],[7,8,9]]

[[1. 2. 3.]
 [7. 8. 9.]]


In [16]:
# Data Centering
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
centered_data = data - mean

# Standardization
std_dev = np.std(data)
standardized_data = (data - mean) / std_dev

# Log Transformation
log_transformed_data = np.log(data)

In [17]:
# Simple Random Sampling Without replacement
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
random_samples = np.random.choice(data, size=5, replace=False)

# Bootstrap Sampling
num_samples = 1000
bootstrap_samples = np.random.choice(data, size=(num_samples, len(data)), replace=True)

In [18]:
A = np.array([[2, 3], [4, 5]])
b = np.array([6, 7])

# Solve Ax = b for x
x = np.linalg.solve(A, b)

In [19]:
print(x)

[-4.5  5. ]


In [20]:
np.matmul(A,x)

array([6., 7.])

In [21]:
import numpy as np
import numpy.ma as ma

# Temperature dataset with missing values (-999 represents missing values)
temperatures = np.array([22.5, 23.0, -999, 24.5, -999, 26.0, 27.2, -999, 28.5])

# Calculate the mean temperature without handling missing values
mean_temperature = np.mean(temperatures)

# Print the result = -316.14 
print("Mean Temperature (without handling missing values):", mean_temperature)

# Create a mask for missing values (-999)
mask = (temperatures == -999)

# Create a masked array
masked_temperatures = ma.masked_array(temperatures, mask=mask)

# Calculate the mean temperature (excluding missing values)
mean_temperature = ma.mean(masked_temperatures)

# Print the result = 25.28
print("Mean Temperature (excluding missing values):", mean_temperature)

Mean Temperature (without handling missing values): -316.14444444444445
Mean Temperature (excluding missing values): 25.28333333333333


In [22]:
import numpy as np

# Define data types for fields
dt = np.dtype([('name', 'S20'), ('age', int), ('salary', float)])

# Create a structured array
employees = np.array([('Alice', 30, 50000.0), ('Bob', 25, 60000.0)], dtype=dt)

# Access the 'name' field of the first employee
print(employees['name'][0])

# Access the 'age' field of all employees
print(employees['age'])

b'Alice'
[30 25]
